workflows:
  sample-workflow:
    name: Codemagic Sample Workflow
    instance_type: mac_mini_m1
    scripts:
      - name: Install dependencies
        script: |
          flutter clean
          flutter pub get
          cd ios
          pod install
          cd ..
      - name: Build iOS app
        script: |
          xcodebuild -allowProvisioningUpdates
          flutter build ios --release
    artifacts:
      - build/ios/ipa

