workflows:
  ios-workflow:
    name: iOS Workflow
    instance_type: mac_mini_m1
    environment:
      groups:
        - app_store_credentials
        - signing_credentials
    scripts:
      - name: Clean build folder
        script: |
          flutter clean
      - name: Install dependencies
        script: |
          flutter pub get
          cd ios
          pod install
          cd ..
      - name: Build iOS app
        script: |
          set -e
          xcodebuild -workspace ios/Runner.xcworkspace \
                     -scheme Runner \
                     -configuration Release \
                     -allowProvisioningUpdates \
                     archive | tee build.log
          xcodebuild -exportArchive \
                     -exportOptionsPlist ios/Runner/ExportOptions.plist \
                     -exportPath build/ipa | tee export.log
    artifacts:
      - build/ipa
      - build.log
      - export.log
