workflows:
  sample-workflow:
    name: Codemagic Sample Workflow
    instance_type: mac_mini_m1
    scripts:
      - name: Install dependencies
        script: |
          flutter pub get
      - name: Build iOS app
        script: |
          flutter build ios --debug --no-codesign
