workflows:
  sample-workflow:
    name: Codemagic Sample Workflow
    instance_type: mac_mini_m1
    environment:
      groups:
        - info
    scripts:
      - name: Install dependencies
        script: |
          flutter clean
          flutter pub get
          cd ios
          pod install
          cd ..
      - name: Build iOS app
        script: |
          xcodebuild -workspace ios/Runner.xcworkspace \
                     -scheme Runner \
                     -configuration Release \
                     -allowProvisioningUpdates \
                     -archivePath build/ios/Runner.xcarchive \
                     archive
          xcodebuild -exportArchive \
                     -archivePath build/ios/Runner.xcarchive \
                     -exportOptionsPlist ios/Runner/ExportOptions.plist \
                     -exportPath build/ios/ipa
    artifacts:
      - build/ios/ipa
